  [
    {
      name: "Promethium",
      symbol: "Pm",
      atomic_number: "61",
      atomic_volume: "",
      atomic_weight: "144.91276",
      mass_number: "126",
      group: "",
      period: "6",
      series: "Lanthanides",
      block: "f",
      electrons: "61",
      protons: "61",
      neutrons: "65",
      cas: "7440-12-2",
      discoverers: "J.A. Marinsky, L.E. Glendenin, C.D. Coryell",
      discovery_location: "United States",
      discovery_year: "1945.0",
      description: "Soft silvery metallic element, belongs to the lanthanoids. Pm-147, the only natural isotope, is radioactive and has a half-life of 252 years. Eighteen radioisotopes have been produced, but all have very short half-lives. Found only in nuclear decay waste. Pm-147 is of interest as a beta-decay source, however Pm-146 and Pm-148 have to be removed from it first, as they generate gamma radiation. Discovered by J.A. Marinsky, L.E. Glendenin and C.D. Coryell in 1947.",
      name_origin: "Named for the Greek god, Prometheus.",
      sources: "Does not occur naturally. Found among fission products of uranium, thorium, and plutonium.",
      uses: "It has been used as a source of radioactivity for thickness-measuring gages.",
      mendeleev_number: "21",
      story: "In 1902, Bohuslav Branner speculated that there should be an element in the periodic table between neodymium and samarium. He was not to know that all its isotopes were radioactive and had long disappeared. Attempts were made to discover it and several claims were made, but clearly all were false. However, minute amounts of promethium do occur in uranium ores as a result of nuclear fission, but in amounts of less than a microgram per million tonnes of ore. In 1939, the 60-inch cyclotron at the University of California was used to make promethium, but it was not proven. Finally element 61 was produced in 1945 by Jacob .A. Marinsky, Lawrence E. Glendenin, and Charles D. Coryell at Oak Ridge, Tennessee. They used ion-exchange chromatography to separate it from the fission products of uranium fuel taken from a nuclear reactor.",
      country: "USA",
      image: "http://res.cloudinary.com/dc2o3efbz/image/upload/v1480909602/elements/promethium.jpg",
      formulas: "['PmCl3', 'Pm2O3', 'Pm2(SO4)3']",
      formulas_cid: "[14475784, ]",
      formula_links: "[]"
    },
    {
      name: "Samarium",
      symbol: "Sm",
      atomic_number: "62",
      atomic_volume: "19.9",
      atomic_weight: "150.36",
      mass_number: "152",
      group: "",
      period: "6",
      series: "Lanthanides",
      block: "f",
      electrons: "62",
      protons: "62",
      neutrons: "90",
      cas: "7440-19-9",
      discoverers: "Paul Émile Lecoq de Boisbaudran",
      discovery_location: "France",
      discovery_year: "1879.0",
      description: "Soft silvery metallic element, belongs to the lanthanoids. Seven natural isotopes, Sm-147 is the only radioisotope, and has a half-life of 2.5*10^11 years. Used for making special alloys needed in the production of nuclear reactors. Also used as a neutron absorber. Small quantities of samarium oxide is used in special optical glasses. The largest use of the element is its ferromagnetic alloy which produces permanent magnets that are five times stronger than magnets produced by any other material. Discovered by Francois Lecoq de Boisbaudran in 1879.",
      name_origin: "Named after the mineral samarskite.",
      sources: "Found with other rare earths in monazite sand. The sand is often 50% rare earths by weight and 2.8% samarium.",
      uses: "It is used in the electronics and ceramics industries.  It is easily magnetized and very difficult to demagnetize. This suggests important future applications in solid-state and superconductor technologies.",
      mendeleev_number: "23",
      story: "Samarium was one of the rare earths (aka lanthanoids) which perplexed and puzzled the chemists of the 1800s. Its history began with the discovery of cerium in 1803. This was suspected of harbouring other metals, and in 1839 Carl Mosander claimed to have obtained lanthanum and didymium from it. While he was right about lanthanum, he was wrong about didymium. In 1879, Paul-Émile Lecoq de Boisbaudran extracted didymium from the mineral samarskite. He then made a solution of didymium nitrate and added ammonium hydroxide. He observed that the precipitate which formed came down in two stages. He concentrated his attention on the first precipitate and measured its spectrum which revealed it to be a new element samarium. Samarium itself was eventually to yield other rare-earths: gadolinium in 1886 and europium in 1901.",
      country: "France",
      image: "http://res.cloudinary.com/dc2o3efbz/image/upload/v1480906169/elements/samarium-2.jpg",
      formulas: "['Sm2O3', 'SmF3', 'SmCl3']",
      formulas_cid: "[23951, 24947, 61508]",
      formula_links: "['/shorts/IQtdruAs68I', '\"\"', '\"\"']"
    },
    {
      name: "Europium",
      symbol: "Eu",
      atomic_number: "63",
      atomic_volume: "28.9",
      atomic_weight: "151.964",
      mass_number: "153",
      group: "",
      period: "6",
      series: "Lanthanides",
      block: "f",
      electrons: "63",
      protons: "63",
      neutrons: "90",
      cas: "7440-53-1",
      discoverers: "Eugène Demarçay",
      discovery_location: "France",
      discovery_year: "1901.0",
      description: "Soft silvery metallic element belonging to the lanthanoids. Eu-151 and Eu-153 are the only two stable isotopes, both of which are Neutron absorbers. Discovered in 1889 by Sir William Crookes.",
      name_origin: "Named for the continent of Europe.",
      sources: "Obtained from monazite sand, which is a mixture of phosphates of calcium, thorium, cerium, and most other rare earths.",
      uses: "Used with yttrium oxide to make red phosphors for color televisions.",
      mendeleev_number: "25",
      story: "Europium’s story is part of the complex history of the rare earths, aka lanthanoids. It began with cerium which was discovered in 1803. In 1839 Carl Mosander separated two other elements from it: lanthanum and one he called didymium which turned out to be a mixture of two rare earths, praseodymium and neodymium, as revealed by Karl Auer in 1879. Even so, it still harboured another rarer metal, samarium, separated by Paul-Émile Lecoq de Boisbaudran, and even that was impure. In 1886 Jean Charles Galissard de Marignac extracted gadolinium, from it, but that was still not the end of the story. In 1901, Eugène-Anatole Demarçay carried out a painstaking sequence of crystallisations of samarium magnesium nitrate, and separated yet another new element: europium.",
      country: "France",
      image: "http://res.cloudinary.com/dc2o3efbz/image/upload/v1480906180/elements/europium-2.jpg",
      formulas: "['Eu2O3', 'EuO', 'EuCl3']",
      formulas_cid: "[159383, 155903113, 24809]",
      formula_links: "['/watch?v=oeXiDjUUvlE&pp=ygUTaG93IHRvIGNyZWF0ZSBFdTJPMw%3D%3D', '\"\"', '/watch?v=etedYSPKH4w&pp=ygUTaG93IHRvIGNyZWF0ZSBFdUNsMw%3D%3D']"
    },
    {
      name: "Gadolinium",
      symbol: "Gd",
      atomic_number: "64",
      atomic_volume: "19.9",
      atomic_weight: "157.25",
      mass_number: "158",
      group: "",
      period: "6",
      series: "Lanthanides",
      block: "f",
      electrons: "64",
      protons: "64",
      neutrons: "94",
      cas: "7440-54-2",
      discoverers: "Jean de Marignac",
      discovery_location: "Switzerland",
      discovery_year: "1880.0",
      description: "Soft silvery metallic element belonging to the lanthanoids. Seven natural, stable isotopes are known in addition to eleven artificial isotopes. Gd-155 and Gd-157 and the best neutron absorbers of all elements. Gadolinium compounds are used in electronics. Discovered by J.C.G Marignac in 1880.",
      name_origin: "Named after the mineral gadolinite.",
      sources: "Found with other rare earths in gadolinite and monazite sand.",
      uses: "Used in steel alloying agents and the manufacture of electronic components.",
      mendeleev_number: "27",
      story: "Gadolinium was discovered in 1880 by Charles Galissard de Marignac at Geneva. He had long suspected that the didymium reported by Carl Mosander was not a new element but a mixture. His suspicions were confirmed when Marc Delafontaine and Paul-Emile Lecoq de Boisbaudran at Paris reported that its spectral lines varied according to the source from which it came. Indeed, in 1879 they had already separated samarium from some didymium which had been extracted from the mineral samarskite, found in the Urals. In 1880, Marignac extracted yet another new rare earth from didymium, as did Paul-Émile Lecoq de Boisbaudran in 1886, and it was the latter who called it gadolinium.",
      country: "Switzerland",
      image: "http://res.cloudinary.com/dc2o3efbz/image/upload/v1480906202/elements/gadolinium-2.jpg",
      formulas: "['Gd2O3', 'Gd2O12S3', 'GdCl3']",
      formulas_cid: "[159427, 166873, 61486]",
      formula_links: "['/shorts/jgZpsBuAWO4?si=ESE1ygFGwK-biykI', '', '/s1PrRUBP-sE?si=l0BDKPLMhGFDy1qz']"
    },
    {
      name: "Terbium",
      symbol: "Tb",
      atomic_number: "65",
      atomic_volume: "19.2",
      atomic_weight: "158.92535",
      mass_number: "159",
      group: "",
      period: "6",
      series: "Lanthanides",
      block: "f",
      electrons: "65",
      protons: "65",
      neutrons: "94",
      cas: "7440-27-9",
      discoverers: "Carl Mosander",
      discovery_location: "Sweden",
      discovery_year: "1843.0",
      description: "Silvery metallic element belonging to the lanthanoids. Tb-159 is the only stable isotope, there are seventeen artificial isotopes. Discovered by G.G. Mosander in 1843.",
      name_origin: "Named after Ytterby, a village in Sweden.",
      sources: "Found with other rare earths in monazite sand, which typically contain 0.03% terbium. Other sources are xenotime and euxenite, both of which are oxide mixtures that can contain up to 1% terbium.",
      uses: "It is used in modest amounts in special lasers and solid-state devices.",
      mendeleev_number: "29",
      story: "Terbium was first isolated in 1843 by the Swedish chemist Carl Mosander at Stockholm. He had already investigated cerium oxide and separated a new element from it, lanthanum, and now he focussed his attention on yttrium, discovered in 1794, because he thought this too might harbour another element. In fact Mosander was able to obtain two other metal oxides from it: terbium oxide (yellow) and erbium oxide (rose pink) and these he announced in 1843. This was not the end of the story, however, because later that century these too yielded other rare earth elements (aka lanthanoids). Today these elements are easily separated by a process known as liquid-liquid extraction.",
      country: "Sweden",
      image: "http://res.cloudinary.com/dc2o3efbz/image/upload/v1480906212/elements/terbium-2.jpg",
      formulas: "['Tb', 'Tb4O7', 'TbCl3']",
      formulas_cid: "[23958, 23956, 61458]",
      formula_links: "['\"\"', '/watch?v=YROyh5foGAc&pp=ygUTaG93IHRvIGNyZWF0ZSBUYjRPNw%3D%3D', '/watch?v=FHdcv0okPQ4&pp=ygUTaG93IHRvIGNyZWF0ZSBUYkNsMw%3D%3D']"
    },
    {
      name: "Dysprosium",
      symbol: "Dy",
      atomic_number: "66",
      atomic_volume: "19.0",
      atomic_weight: "162.5",
      mass_number: "164",
      group: "",
      period: "6",
      series: "Lanthanides",
      block: "f",
      electrons: "66",
      protons: "66",
      neutrons: "98",
      cas: "7429-91-6",
      discoverers: "Paul Émile Lecoq de Boisbaudran",
      discovery_location: "France",
      discovery_year: "1886.0",
      description: "Metallic with a bright silvery-white lustre. Dysprosium belongs to the lanthanoids. It is relatively stable in air at room temperatures, it will however dissolve in mineral acids, evolving hydrogen. It is found in from rare-earth minerals. There are seven natural isotopes of dysprosium, and eight radioisotopes, Dy-154 being the most stable with a half-life of 3*10^6 years. Dysprosium is used as a neutron absorber in nuclear fission reactions, and in compact disks. It was discovered by Paul Emile Lecoq de Boisbaudran in 1886 in France. Its name comes from the Greek word dysprositos, which means hard to obtain.",
      name_origin: "Greek: dysprositos (hard to get at).",
      sources: "Usually found with erbium, holmium and other rare earths in some minerals such as monazite sand, which is often 50% rare earth by weight.",
      uses: "Its uses are limited to the experimental and esoteric.",
      mendeleev_number: "31",
      story: "Dysprosium was discovered in 1886 by Paul-Émile Lecoq de Boisbaudran in Paris. Its discovery came as a result of research into yttrium oxide, first made in 1794, and from which other rare earths (aka lanthanoids) were subsequently to be extracted, namely erbium in 1843, then holmium in 1878, and finally dysprosium. De Boisbaudran’s method had involved endless precipitations carried out on the marble slab of his fireplace at home. Pure samples of dysprosium were not available until Frank Spedding and co-workers at Iowa State University developed the technique of ion-exchange chromatography around 1950. From then on it was possible to separate the rare earth elements in a reliable and efficient manner, although that method of separation has now been superseded by liquid-liquid exchange technology.",
      country: "France",
      image: "http://res.cloudinary.com/dc2o3efbz/image/upload/v1480906225/elements/dysprosium.jpg",
      formulas: "['Dy', 'Dy2O3', 'DyN3O9']",
      formulas_cid: "[23912, 159370, 25007]",
      formula_links: "['\"\"', '/watch?v=8IFsOmriS8I&pp=ygUTaG93IHRvIGNyZWF0ZSBEeTJPMw%3D%3D', '/watch?v=eHBBa2gMhzc&pp=ygUTaG93IHRvIGNyZWF0ZSBEeUNsMw%3D%3D']"
    },
    {
      name: "Holmium",
      symbol: "Ho",
      atomic_number: "67",
      atomic_volume: "18.7",
      atomic_weight: "164.93033",
      mass_number: "165",
      group: "",
      period: "6",
      series: "Lanthanides",
      block: "f",
      electrons: "67",
      protons: "67",
      neutrons: "98",
      cas: "7440-60-0",
      discoverers: "J.L. Soret",
      discovery_location: "Switzerland",
      discovery_year: "1878.0",
      description: "Relatively soft and malleable silvery-white metallic element, which is stable in dry air at room temperature. It oxidizes in moist air and at high temperatures. It belongs to the lanthanoids. A rare-earth metal, it is found in the minerals monazite and gadolinite. It possesses unusual magnetic properties. One natural isotope, Ho-165 exists, six radioisotopes exist, the most stable being Ho-163 with a half-life of 4570 years. Holmium is used in some metal alloys, it is also said to stimulate the metabolism. Discovered by Per Theodor Cleve and J.L. Soret in Switzerland in 1879. The name homium comes from the Greek word Holmia which means Sweden. While all holmium compounds should be considered highly toxic, initial evidence seems to indicate that they do not pose much danger. The metal's dust however, is a fire hazard.",
      name_origin: "From Holmia, the Latinized name for Stockholm, Sweden.",
      sources: "Occurs in gadolinite. Most often from monazite which is often 50% rare earth and typically 0.05% holmium.",
      uses: "It has very few practical applications; however, it has some unusual magnetic properties that offer some hope for future applications.",
      mendeleev_number: "33",
      story: "Holmium was discovered at Geneva in 1878 by Marc Delafontaine and Louis Soret, and independently by Per Teodor Cleve at Uppsala, Sweden. Both teams were investigating yttrium, which was contaminated with traces of other rare earths (aka lanthanoids) and had already yielded erbium which was later to yield ytterbium. Cleve looked more closely at what remained after the ytterbium had been removed, and realised it must contain yet other elements because he found that its atomic weight depended on its source. He separated holmium from erbium in 1878. Delafontaine and Soret also extracted it from the same source, having seen unexplained lines in the atomic spectrum. We cannot be certain that either group had produced a pure sample of the new element because yet another rare-earth, dysprosium, was to be extracted from holmium.",
      country: "Sweden",
      image: "http://res.cloudinary.com/dc2o3efbz/image/upload/v1480906237/elements/holmium-2.jpg",
      formulas: "['Ho2O3', 'HoN', 'HoCl3']",
      formulas_cid: "[159423, 82818, 24992]",
      formula_links: "['/watch?v=Uqvq6rPazBc&pp=ygUTaG93IHRvIGNyZWF0ZSBIbzJPMw%3D%3D', '\"\"', '/oQLhQWOgm24?si=c0F08pQEK9IMqfIE']"
    },
    {
      name: "Erbium",
      symbol: "Er",
      atomic_number: "68",
      atomic_volume: "18.4",
      atomic_weight: "167.259",
      mass_number: "166",
      group: "",
      period: "6",
      series: "Lanthanides",
      block: "f",
      electrons: "68",
      protons: "68",
      neutrons: "98",
      cas: "7440-52-0",
      discoverers: "Carl Mosander",
      discovery_location: "Sweden",
      discovery_year: "1843.0",
      description: "Soft silvery metallic element which belongs to the lanthanoids. Six natural isotopes that are stable. Twelve artificial isotopes are known. Used in nuclear technology as a neutron absorber. It is being investigated for other possible uses. Discovered by Carl G. Mosander in 1843.",
      name_origin: "Named after the Swedish town, Ytterby.",
      sources: "Found with other heavier rare earths in xenotime and euxerite.",
      uses: "Erbium oxide is used in ceramics to obtain a pink glaze. Also a few uses in the nuclear industry and as an alloying agent for other exotic metals. For example, it increases the malleability of vanadium.",
      mendeleev_number: "35",
      story: "In 1843, at Stockholm, Carl Mosander obtained two new metal oxides from yttrium, which had been know since 1794. One of these was erbium oxide, which was pink. (The other was terbium oxide, which was yellow.) While erbium was one of the first lanthanoid elements to be discovered, the picture is clouded because early samples of this element must have contained other rare-earths. We know this because In1878 Jean-Charles Galissard de Marignac, working at the University of Geneva, extracted another element from erbium and called it ytterbium. (This too was impure and scandium was extracted from it a year later.) A sample of pure erbium metal was not produced until 1934, when Wilhelm Klemm and Heinrich Bommer achieved it by heating purified erbium chloride with potassium.",
      country: "Sweden",
      image: "http://res.cloudinary.com/dc2o3efbz/image/upload/v1480906262/elements/erbium-2.jpg",
      formulas: "['Er2O3', 'ErF3', 'ErCl3']",
      formulas_cid: "[24851919, 24939, 66277]",
      formula_links: "['/watch?v=27rULQ342KQ&pp=ygUTaG93IHRvIGNyZWF0ZSBFcjJPMw%3D%3D', '/watch?v=qIwrhUrvX-k&pp=ygUSaG93IHRvIGNyZWF0ZSBFckYz', '/watch?v=mfpGhbfvHFI&pp=ygUTaG93IHRvIGNyZWF0ZSBFckNsMw%3D%3D']"
    },
    {
      name: "Thulium",
      symbol: "Tm",
      atomic_number: "69",
      atomic_volume: "18.1",
      atomic_weight: "168.93422",
      mass_number: "169",
      group: "",
      period: "6",
      series: "Lanthanides",
      block: "f",
      electrons: "69",
      protons: "69",
      neutrons: "100",
      cas: "7440-30-4",
      discoverers: "Per Theodor Cleve",
      discovery_location: "Sweden",
      discovery_year: "1879.0",
      description: "Soft grey metallic element that belongs to the lanthanoids. One natural isotope exists, Tm-169, and seventeen artificial isotopes have been produced. No known uses for the element. Discovered in 1879 by Per Theodor Cleve.",
      name_origin: "From Thule ancient name of Scandinavia.",
      sources: "Found with other rare earths in the minerals gadolinite, euxenite, xenotime, and monazite. Monazite is often 50% rare earth by weight and 0.007% thulium.",
      uses: "Radioactive thulium is used to power portable x-ray machines, eliminating the need for electrical equipment.",
      mendeleev_number: "37",
      story: "Thulium was first isolated in 1879 as its oxide by Per Teodor Cleve at the University of Uppsala, Sweden. The discoveries of the many rare earth elements (aka lanthanoid) began with yttrium in 1794. This was contaminated with these chemically similar elements. Indeed the early chemists were unaware they were there. In 1843, erbium and terbium were extracted from yttrium, and then, in 1874, Cleve looked more closely at erbium and realised that it must contain yet other elements because he observed that its atomic weight varied slightly depending on the source from which it came. He extracted thulium from it in 1879. In 1911, the American chemist Theodore William Richards performed 15,000 recrystallisations of thulium bromate in order to obtain an absolutley pure sample of the element and so determine exactly its atomic weight.",
      country: "Sweden",
      image: "http://res.cloudinary.com/dc2o3efbz/image/upload/v1480906271/elements/thulium-2.jpg",
      formulas: "['Tm2O3', 'TmCl3', 'TmF3']",
      formulas_cid: "[166838, 22154012, 23938]",
      formula_links: "['/_zDo1xe-SYE?si=TD2zMbM8xXcLQ7IG', '\"\"', '\"\"']"
    },
    {
      name: "Ytterbium",
      symbol: "Yb",
      atomic_number: "70",
      atomic_volume: "24.8",
      atomic_weight: "173.045",
      mass_number: "174",
      group: "",
      period: "6",
      series: "Lanthanides",
      block: "f",
      electrons: "70",
      protons: "70",
      neutrons: "104",
      cas: "7440-64-4",
      discoverers: "Jean de Marignac",
      discovery_location: "Switzerland",
      discovery_year: "1878.0",
      description: "Silvery metallic element of the lanthanoids. Seven natural isotopes and ten artificial isotopes are known. Used in certain steels. Discovered by J.D.G. Marignac in 1878.",
      name_origin: "Named for the Swedish village of Ytterby.",
      sources: "Found in minerals such as yttria, monazite, gadolinite, and xenotime. Monazite is often 50% rare earth by weight and typically 0.03% ytterbium.",
      uses: "Used in metallurgical and chemical experiments.",
      mendeleev_number: "39",
      story: "Ytterbium was isolated in 1878 by Jean Charles Galissard de Marignac at the University of Geneva. The story began with yttrium, discovered in 1794, which was contaminated with other rare-earth elements (aka lanthanoids). In 1843, erbium and terbium were extracted from it, and then in 1878, de Marignac separated ytterbium from erbium. He heated erbium nitrate until it decomposed and then extracted the residue with water and obtained two oxides: a red one which was erbium oxide, and a white one which he knew must be a new element, and this he named ytterbium. Even this was eventually shown to contain another rare earth, lutetium, in 1907. A tiny amount of ytterbium metal was made in 1937 by heating ytterbium chloride and potassium together but was impure. Only in 1953 was a pure sample obtained.",
      country: "Switzerland",
      image: "http://res.cloudinary.com/dc2o3efbz/image/upload/v1480906280/elements/ytterbium-2.jpg",
      formulas: "['Yb2O3', 'YbF3', 'YbCl3']",
      formulas_cid: "[159379, 101540173, 61510]",
      formula_links: "['/xWAHdZFznFc', '/watch?v=zcaUowXfiHk&pp=ygUSaG93IHRvIGNyZWF0ZSBZYkYz', '/watch?v=V8mHiFYmlBc&pp=ugMICgJ2aRABGAHKBRNob3cgdG8gY3JlYXRlIFliQ2wz']"
    },
    {
      name: "Lutetium",
      symbol: "Lu",
      atomic_number: "71",
      atomic_volume: "17.8",
      atomic_weight: "174.9668",
      mass_number: "175",
      group: "",
      period: "6",
      series: "Transition metals",
      block: "f",
      electrons: "71",
      protons: "71",
      neutrons: "104",
      cas: "7439-94-3",
      discoverers: "Georges Urbain",
      discovery_location: "France",
      discovery_year: "1907.0",
      description: "Silvery-white rare-earth metal which is relatively stable in air. It happens to be the most expensive rare-earth metal. Its found with almost all rare-earth metals, but is very difficult to separate from other elements. Least abundant of all natural elements. Used in metal alloys, and as a catalyst in various processes. There are two natural, stable isotopes, and seven radioisotopes, the most stable being Lu-174 with a half-life of 3.3 years. The separation of lutetium from Ytterbium was described by Georges Urbain in 1907. It was discovered at approximately the same time by Carl Auer von Welsbach. The name comes from the Greek word lutetia which means Paris.",
      name_origin: "Named for the ancient name of Paris, Lutecia.",
      sources: "Found with ytterbium in gadolinite and xenotime. Usually obtained from monazite sand which is ofter 50% rare earth by weight and 0.003% lutetium.",
      uses: "It has no practical applications.",
      mendeleev_number: "41",
      story: "The honour of discovering lutetium went to Georges Urbain at the Sorbonne in Paris, because he was the first to report it. The story began with the discovery of yttrium in 1794 from which several other elements – the rare earths (aka lanthanoids) – were to be separated, starting with erbium in 1843 and ending with lutetium in 1907. Other chemists, namely Karl Auer in Germany and Charles James in the USA, were about to make the same discovery. Indeed James, who was at the University of New Hampshire, was ahead of Urbain and had extracted quite a lot of the new metal, but he delayed publishing his research. A sample of pure lutetium metal itself was not made until 1953.",
      country: "France",
      image: "http://res.cloudinary.com/dc2o3efbz/image/upload/v1480906296/elements/lutetium-2.jpg",
      formulas: "['LuF3', 'Lu2O3', 'LuCl3']",
      formulas_cid: "[161305, 160904, 24919]",
      formula_links: "['/watch?v=J9hp_cYusFE&pp=ygUSaG93IHRvIGNyZWF0ZSBMdUYz', '/watch?v=Vr1m9d9e8YY&pp=ygUTaG93IHRvIGNyZWF0ZSBMdTJPMw%3D%3D', '\"\"']"
    },
    {
      name: "Hafnium",
      symbol: "Hf",
      atomic_number: "72",
      atomic_volume: "13.6",
      atomic_weight: "178.49",
      mass_number: "180",
      group: "<Group(symbol=IVB, name=)>",
      period: "6",
      series: "Transition metals",
      block: "d",
      electrons: "72",
      protons: "72",
      neutrons: "108",
      cas: "7440-58-6",
      discoverers: "Dirk Coster, Georg von Hevesy",
      discovery_location: "Denmark",
      discovery_year: "1923.0",
      description: "Silvery lustrous metallic transition element. Used in tungsten alloys in filaments and electrodes, also acts as a neutron absorber. First reported by Urbain in 1911, existence was finally established in 1923 by D. Coster, G.C. de Hevesy in 1923.",
      name_origin: "From Hafnia, the Latin name of Copenhagen.",
      sources: "Obtained from mineral zircon or baddeleyite.",
      uses: "Used in reactor control rods because of its ability to absorb neutrons.",
      mendeleev_number: "45",
      story: "In 1911, Georges Urbain reported the discovery of the missing element below zirconium in the periodic table, but he was wrong and the search continued. It was finally discovered by George Charles de Hevesy and Dirk Coster at the University of Copenhagen in 1923. It was found in a zirconium mineral, a Norwegian zircon, but it had proved very difficult to separate it from zirconium and this explained why hafnium remained undiscovered for so long. Other zirconium minerals were now examined by Hevesy, and some were found to contain as much as five per cent of hafnium. (It meant the atomic weight of zirconium was wrong and hafnium-free material had to be produced in order for this to be determined.) The first pure sample of hafnium itself was made in 1925 by decomposing hafnium tetra-iodide over a hot tungsten wire.",
      country: "Denmark",
      image: "http://res.cloudinary.com/dc2o3efbz/image/upload/v1480905532/elements/hafnium-2.jpg",
      formulas: "['HfO2', 'HfCl4', 'HfN']",
      formulas_cid: "[10154082, 37715, 59281403]",
      formula_links: "['/watch?v=HUsOMnV65jk&pp=ygUSaG93IHRvIGNyZWF0ZSBIZk8y', '/shorts/3rSNKQMVGvw', '/watch?v=R49AElOtezw&pp=ygURaG93IHRvIGNyZWF0ZSBIZk4%3D']"
    },
    {
      name: "Tantalum",
      symbol: "Ta",
      atomic_number: "73",
      atomic_volume: "10.9",
      atomic_weight: "180.94788",
      mass_number: "181",
      group: "<Group(symbol=VB, name=)>",
      period: "6",
      series: "Transition metals",
      block: "d",
      electrons: "73",
      protons: "73",
      neutrons: "108",
      cas: "7440-25-7",
      discoverers: "Anders Ekeberg",
      discovery_location: "Sweden",
      discovery_year: "1802.0",
      description: "Heavy blue-grey metallic transition element. Ta-181 is a stable isotope, and Ta-180 is a radioactive isotope, with a half-life in excess of 10^7 years. Used in surgery as it is unreactive. Forms a passive oxide layer in air. Identified in 1802 by Ekeberg and isolated in 1820 by Jons J. Berzelius.",
      name_origin: "From king Tantalus of Greek mythology, father of Niobe.",
      sources: "Chiefly occurs in the mineral tantalite. Always found with niobium.",
      uses: "Often used as an economical substitute for platinum. Tantalum pentoxide is used in capacitors and in camera lenses to increase refracting power. It and its alloys are corrosion and wear resistant so it is used to make surgical and dental tools.",
      mendeleev_number: "49",
      story: "Tantalum was reported as a new metal in 1802 by Anders Gustav Ekeberg at Uppsala University, Sweden. However, when William Wollaston analysed the minerals from which it had been extracted he declared it was identical to niobium which has been discovered the year previously. It was as a result of their similarity that there was confusion regarding their identification. These two elements often occur together and, being chemically very similar, were difficult to separate by the methods available at the time of the discovery. It was not until 1846 that Heinrich Rose separated tantalum and niobium and proved conclusively that they were different elements, and yet his sample of tantalum was still somewhat impure, and it was not until 1903 that pure tantalum was produced by Werner von Bolton.",
      country: "Sweden",
      image: "http://res.cloudinary.com/dc2o3efbz/image/upload/v1480905541/elements/tantalum-2.jpg",
      formulas: "['Ta2O5', 'TaC', 'TaN']",
      formulas_cid: "[104214, 24065, 5969]",
      formula_links: "['/XA3xFWVJsbI&pp=ygUTaG93IHRvIGNyZWF0ZSBUYTJPNQ%3D%3D', '\"\"', '/RjVrFE4V1L4?si=EKFqeD6tc_CfnNKI']"
    },
    {
      name: "Tungsten",
      symbol: "W",
      atomic_number: "74",
      atomic_volume: "9.53",
      atomic_weight: "183.84",
      mass_number: "184",
      group: "<Group(symbol=VIB, name=)>",
      period: "6",
      series: "Transition metals",
      block: "d",
      electrons: "74",
      protons: "74",
      neutrons: "110",
      cas: "7440-33-7",
      discoverers: "Fausto and Juan José de Elhuyar",
      discovery_location: "Spain",
      discovery_year: "1783.0",
      description: "White or grey metallic transition element,formerly called Wolfram. Forms a protective oxide in air and can be oxidized at high temperature. First isolated by Jose and Fausto de Elhuyer in 1783.",
      name_origin: "Swedish: tung sten (heavy stone): symbol from its German name wolfram.",
      sources: "Occurs in the minerals scheelite (CaWO4) and wolframite [(Fe,Mn)WO4].",
      uses: "Made into filaments for vacuum tubes and electric lights. Also as contact points in cars. Combined with calcium or magnesium it makes phosphors. Tungsten carbide is extremely hard and is used for making cutting tools and abrasives.",
      mendeleev_number: "53",
      story: "More than 350 years ago, porcelain makers in China incorporated a unique peach colour into their designs by means of a tungsten pigment that was not known in the West. Indeed it was not for another century that chemists in Europe became aware of it. In 1779, Peter Woulfe examined a mineral from Sweden and concluded it contained a new metal, but he did not separate it. Then in 1781, Wilhelm Scheele investigated it and succeeded in isolating an acidic white oxide and which he rightly deduced was the oxide of a new metal. The credit for discovering tungsten goes to the brothers, Juan and Fausto Elhuyar, who were interested in mineralogy and were based at the Seminary at Vergara, in Spain, 1783 they produced the same acidic metal oxide and even reduced it to tungsten metal by heating with carbon.",
      country: "Spain",
      image: "http://res.cloudinary.com/dc2o3efbz/image/upload/v1480905548/elements/tungsten-rod-2.jpg",
      formulas: "['W', 'WC', 'WB']",
      formulas_cid: "[23964, 19762195, 82793]",
      formula_links: "['/6XxcVg2Dfck?si=ICKSSaOXXAhYfAhq', '/watch?v=vAhzUqYpL3Q&pp=ygUQaG93IHRvIGNyZWF0ZSBXQw%3D%3D', '\"\"']"
    },
    {
      name: "Rhenium",
      symbol: "Re",
      atomic_number: "75",
      atomic_volume: "8.85",
      atomic_weight: "186.207",
      mass_number: "187",
      group: "<Group(symbol=VIIB, name=)>",
      period: "6",
      series: "Transition metals",
      block: "d",
      electrons: "75",
      protons: "75",
      neutrons: "112",
      cas: "7440-15-5",
      discoverers: "Walter Noddack, Ida Tacke, Otto Berg",
      discovery_location: "Germany",
      discovery_year: "1925.0",
      description: "Silvery-white metallic transition element. Obtained as a by-product of molybdenum refinement. Rhenium-molybdenum alloys are superconducting.",
      name_origin: "Latin: Rhenus, the Rhine River.",
      sources: "Found in small amounts in gadolinite and molybdenite. Has a very high melting point.",
      uses: "Mixed with tungsten or platinum to make filaments for mass spectrographs. Its main value is as a trace alloying agent for hardening metal components that are subjected to continuous frictional forces.",
      mendeleev_number: "57",
      story: "The periodic table had two vacant slots below manganese and finding these missing elements, technetium and rhenium, proved difficult. Rhenium was the lower one and indeed it was the last stable, non-radioactive, naturally-occurring element to be discovered. In 1905, Masataka Ogawa found it in the mineral thorianite from Sri Lanka. He realised from lines in its atomic spectrum that it contained an unknown element. He wrongly thought it was the one directly below manganese and so his claim was discounted at the time. However, a re-examination of Ogawa’s original photographic spectra proved he had discovered rhenium. The isolation of rhenium was finally achieved in May 1925 by Walter Noddack and Ida Tacke working in Berlin. They concentrated it from the ore gadolinite in which it was an impurity.",
      country: "Germany",
      image: "http://res.cloudinary.com/dc2o3efbz/image/upload/v1480905555/elements/rhenium-4.jpg",
      formulas: "['Re2O7', 'ReO4', 'ReO3']",
      formulas_cid: "[123106, 24547, 102110]",
      formula_links: "['/watch?v=5dlnnoCNVlY', '/watch?v=reO4-vNeC3o&pp=ygUSaG93IHRvIGNyZWF0ZSBSZU80', '/watch?v=c8EZaUBLhjQ&pp=ygUSaG93IHRvIGNyZWF0ZSBSZU8z']"
    },
    {
      name: "Osmium",
      symbol: "Os",
      atomic_number: "76",
      atomic_volume: "8.43",
      atomic_weight: "190.23",
      mass_number: "192",
      group: "<Group(symbol=VIIIB, name=)>",
      period: "6",
      series: "Transition metals",
      block: "d",
      electrons: "76",
      protons: "76",
      neutrons: "116",
      cas: "7440-04-2",
      discoverers: "Smithson Tenant",
      discovery_location: "England",
      discovery_year: "1804.0",
      description: "Hard blue-white metallic transition element. Found with platinum and used in some alloys with platinum and iridium.",
      name_origin: "Greek: osmê (odor).",
      sources: "Obtained from the same ores as platinum.",
      uses: "Used to tip gold pen points, instrument pivots, to make electric light filaments. Used for high temp. alloys and pressure bearings. Very hard and resists corrosion better than any other.",
      mendeleev_number: "61",
      story: "In 1803, Smithson Tennant added platinum to dilute aqua regia, which is a mixture of nitric and hydrochloric acids, and observed that not all the metal went into solution. Earlier experimenters had assumed that the residue was graphite, but he suspected it was something else, and he began to investigate it. By a combination of acid and alkali treatments he eventually separated it into two new metal elements, which he named iridium and osmium, naming the latter on account of the strong odour it gave off. Its name is derived from osme the Greek word for smell. Although it was recognised as a new metal, little use was made of it because it was rare and difficult to work with, although it was extremely hard wearing and for several years it was used for pen nibs and gramophone needles.",
      country: "UK",
      image: "http://res.cloudinary.com/dc2o3efbz/image/upload/v1480905571/elements/osmium-2.jpg",
      formulas: "['OsO4', 'OsCl3', 'Os']",
      formulas_cid: "[30318, 83468, 23937]",
      formula_links: "['', '', '/AdX-T2Vv68Y?si=jbbDOTxjotLyJYBT']"
    },
    {
      name: "Iridium",
      symbol: "Ir",
      atomic_number: "77",
      atomic_volume: "8.54",
      atomic_weight: "192.217",
      mass_number: "193",
      group: "<Group(symbol=VIIIB, name=)>",
      period: "6",
      series: "Transition metals",
      block: "d",
      electrons: "77",
      protons: "77",
      neutrons: "116",
      cas: "7439-88-5",
      discoverers: "S.Tenant, A.F.Fourcory, L.N.Vauquelin, H.V.Collet-Descoltils",
      discovery_location: "England/France",
      discovery_year: "1804.0",
      description: "Very hard and brittle, silvery metallic transition element. It has a yellowish cast to it. Salts of iridium are highly colored. It is the most corrosion resistant metal known, not attacked by any acid, but is attacked by molten salts. There are two natural isotopes of iridium, and 4 radioisotopes, the most stable being Ir-192 with a half-life of 73.83 days. Ir-192 decays into Platinum, while the other radioisotopes decay into Osmium. Iridium is used in high temperature apparatus, electrical contacts, and as a hardening agent for platinumpy. Discovered in 1803 by Smithson Tennant in England. The name comes from the Greek word iris, which means rainbow. Iridium metal is generally non-toxic due to its relative unreactivity, but iridium compounds should be considered highly toxic.",
      name_origin: "Latin: iris (rainbow).",
      sources: "Found in gravel deposits with platinum.",
      uses: "Used with osmium to tip gold pen points, to make crucible and special containers. Also to make alloys used for standard weights and measures, and heat-resistant alloys. Also as hardening agent for platinum.",
      mendeleev_number: "65",
      story: "Iridium was discovered together with osmium in1803 by Smithson Tennant in London. When crude platinum was dissolved in dilute aqua regia, which is a mixture of nitric and hydrochloric acids, it left behind a black residue thought to be graphite. Tennant thought otherwise, and by treating it alternately with alkalis and acids he was able to separate it into two new elements. These he announced at the Royal Institution in London, naming one iridium, because its salts were so colourful and the other osmium because it had a curious odour (see osmium). Despite its seeming intractability, a group of chemists, including the great Humphry Davy, demonstrated in 1813 that iridium would indeed melt like other metals. To achieve this they exposed it to the powerful current generated by a large array of batteries.",
      country: "UK",
      image: "http://res.cloudinary.com/dc2o3efbz/image/upload/v1480905580/elements/iridium-2.jpg",
      formulas: "['IrO2', 'IrCl3', 'IrF6']",
      formulas_cid: "[82821, 25563, 24546]",
      formula_links: "['/watch?v=v4fw7BfJm0E&pp=ygUSaG93IHRvIGNyZWF0ZSBJck8y', '\"\"', '\"\"']"
    },
    {
      name: "Platinum",
      symbol: "Pt",
      atomic_number: "78",
      atomic_volume: "9.1",
      atomic_weight: "195.084",
      mass_number: "195",
      group: "<Group(symbol=VIIIB, name=)>",
      period: "6",
      series: "Transition metals",
      block: "d",
      electrons: "78",
      protons: "78",
      neutrons: "117",
      cas: "7440-06-4",
      discoverers: "Julius Scaliger",
      discovery_location: "Italy",
      discovery_year: "1735.0",
      description: "Attractive greyish-white metal. When pure, it is malleable and ductile. Does not oxidize in air, insoluble in hydrochloric and nitric acid. Corroded by halogens, cyandies, sulphur and alkalis. Hydrogen and Oxygen react explosively in the presence of platinumpy. There are six stable isotopes and three radioisotopes, the most stable being Pt-193 with a half-life of 60 years. Platinum is used in jewelry, laboratory equipment, electrical contacts, dentistry, and anti-pollution devices in cars. PtCl2(NH3)2 is used to treat some forms of cancer. Platinum-Cobalt alloys have magnetic properties. It is also used in the definition of the Standard Hydrogen Electrode. Discovered by Antonio de Ulloa in South America in 1735. The name comes from the Spanish word platina which means silver. Platinum metal is generally not a health concern due to its unreactivity, however platinum compounds should be considered highly toxic.",
      name_origin: "Spanish: platina (little silver).",
      sources: "Produced from deposits of native, or elemental, platinum.",
      uses: "Used in jewelry, to make crucible and special containers and as a catalyst. Used with cobalt to produce very strong magnets. Also to make standard weights and measures. Resists corrosion and acid attacks except aqua regia.",
      mendeleev_number: "69",
      story: "Probably the oldest worked specimen of platinum is that from an ancient Egyptian casket of the 7th century BC, unearthed at Thebes and dedicated to Queen Shapenapit. Otherwise this metal was unknown in Europe and Asia for the next two millennia, although on the Pacific coast of South America, there were people able to work platinum, as shown by burial goods dating back 2000 years. In 1557 an Italian scholar, Julius Scaliger, wrote of a metal from Spanish Central America that could not be made to melt and was no doubt platinum. Then, in 1735, Antonio Ulloa encountered this curious metal, but as he returned to Europe his ship was captured by the Royal Navy and he ended up in London. There, members of the Royal Society were most interested to hear about the new metal, and by the 1750s, platinum was being reported and discussed throughout Europe.",
      country: "Spain",
      image: "http://res.cloudinary.com/dc2o3efbz/image/upload/v1480905590/elements/platinum-2.jpg",
      formulas: "['PtCl2', 'PtO2', 'H2PtCl6']",
      formulas_cid: "[26012, 345198, 11281299]",
      formula_links: "['/watch?v=HS_pYc3VW3w&pp=ygUTaG93IHRvIGNyZWF0ZSBQdENsMg%3D%3D', '\"\"', '/shorts/vidXQK7hE5M']"
    },
    {
      name: "Gold",
      symbol: "Au",
      atomic_number: "79",
      atomic_volume: "10.2",
      atomic_weight: "196.966569",
      mass_number: "197",
      group: "<Group(symbol=IB, name=Coinage metals)>",
      period: "6",
      series: "Transition metals",
      block: "d",
      electrons: "79",
      protons: "79",
      neutrons: "118",
      cas: "7440-57-5",
      discoverers: "Known to the ancients.",
      discovery_location: "",
      discovery_year: "",
      description: "Gold is gold colored. It is the most malleable and ductile metal known. There is only one stable isotope of gold, and five radioisotopes of gold, Au-195 being the most stable with a half-life of 186 days. Gold is used as a monetary standard, in jewelry, dentistry, electronics. Au-198 is used in treating cancer and some other medical conditions. Gold has been known to exist as far back as 2600 BC. Gold comes from the Anglo-Saxon word gold. Its symbol, Au, comes from the Latin word aurum, which means gold. Gold is not particularly toxic, however it is known to cause damage to the liver and kidneys in some.",
      name_origin: "Anglo-Saxon: geolo (yellow); symbol from Latin: aurum (shining dawn).",
      sources: "Found in veins in the crust, with cooper ore and native .",
      uses: "Very malleable. Used in electronics, jewelry and coins. It is a good reflector of infrared radiation, so a thin film of gold is applied to the glass of skyscrapers to reduce internal heating from sunlight.",
      mendeleev_number: "73",
      story: "Gold has been known since prehistoric times and was one of the first metals to be worked, mainly because it was to be found as nuggets or as particles in the beds of streams. Such was the demand that by 2000 BC the Egyptians began mining gold. The death mask of Tutankhamen, who died in 1323 BC, contained 100 kg of the metal. The royal graves of ancient Ur (modern Iraq), which flourished from 3800 to 2000 BC, also contained gold objects. The minting of gold coins began around 640 BC in the Kingdom of Lydia (situated in what is now modern Turkey) using electrum, a native alloy of gold and silver. The first pure gold coins were minted in the reign of King Croesus, who ruled from 561–547 BC.",
      country: "ancient",
      image: "http://res.cloudinary.com/dc2o3efbz/image/upload/v1480905599/elements/gold-2.jpg",
      formulas: "['Au', 'AuCl3', 'Au2S3']",
      formulas_cid: "[23985, 26030, 10313289]",
      formula_links: "['/watch?v=KQBLL_JRhWs&pp=ygUQaG93IHRvIGNyZWF0ZSBBdQ%3D%3D', '/watch?v=ITnvgILX4ug&pp=ygUTaG93IHRvIGNyZWF0ZSBBdUNsMw%3D%3D', '\"\"']"
    },
    {
      name: "Mercury",
      symbol: "Hg",
      atomic_number: "80",
      atomic_volume: "14.8",
      atomic_weight: "200.592",
      mass_number: "202",
      group: "<Group(symbol=IIB, name=)>",
      period: "6",
      series: "Transition metals",
      block: "d",
      electrons: "80",
      protons: "80",
      neutrons: "122",
      cas: "7439-97-6",
      discoverers: "Known to the ancients.",
      discovery_location: "",
      discovery_year: "",
      description: "Heavy silvery liquid metallic element, belongs to the zinc group. Used in thermometers, barometers and other scientific apparatus. Less reactive than zinc and cadmium, does not displace hydrogen from acids. Forms a number of complexes and organomercury compounds.",
      name_origin: "From the Roman god Mercury; symbol from Latin: hydrargyrus (liquid silver).",
      sources: "Virtually all mercury comes from cinnabar or mercury sulfide (HgS). Some sources of red cinnabar are so rich in mercury that droplets of elemental mercury can be found in random samples.",
      uses: "Used in thermometers, barometers, and batteries. Also used in electrical switches and mercury-vapor lighting products.",
      mendeleev_number: "79",
      story: "Cinnabar (aka vermilion, mercury sulfide, HgS), was used as a bright red pigment by the Palaeolithic painters of 30,000 years ago to decorate caves in Spain and France. Cinnabar would yield up its mercury simply on heating in a crucible, and the metal fascinated people because it was a liquid that would dissolve gold. The ancients used in on a large scale to extract alluvial gold from the sediment of rivers. The mercury dissolved the gold which could be reclaimed by distilling off the mercury. The Almadén deposit in Spain provided Europe with its mercury. In the Americas, it was the Spanish conquerors who exploited the large deposits of cinnabar at Huancavelica in order to extract gold. In 1848 the miners of the Californian Gold Rush used mercury from the New Almaden Mines of California. Although highly toxic, mercury had many uses, as in thermometers, but these are now strictly curtained.",
      country: "ancient",
      image: "http://res.cloudinary.com/dc2o3efbz/image/upload/v1480909981/elements/mercury.jpg",
      formulas: "['HgO', 'HgS', 'HgCl2']",
      formulas_cid: "[18318, 44517647, 24085]",
      formula_links: "['/_Y1alDuXm6A?si=M_9XUkO3QXByJjMG', '/watch?v=EB3WV3tuFEI&pp=ygURaG93IHRvIGNyZWF0ZSBIZ1M%3D', '/watch?v=1CPwmXnihkk&pp=ygUTaG93IHRvIGNyZWF0ZSBIZ0NsMg%3D%3D']"
    },
    {
      name: "Thallium",
      symbol: "Tl",
      atomic_number: "81",
      atomic_volume: "17.2",
      atomic_weight: "204.38",
      mass_number: "205",
      group: "<Group(symbol=IIIA, name=Boron group)>",
      period: "6",
      series: "Poor metals",
      block: "p",
      electrons: "81",
      protons: "81",
      neutrons: "124",
      cas: "7440-28-0",
      discoverers: "Sir William Crookes",
      discovery_location: "England",
      discovery_year: "1861.0",
      description: "Pure, unreacted thallium appears silvery-white and exhibits a metallic lustre. Upon reacting with air, it begins to turn bluish-grey and looks like lead. It is very malleable, and can be cut with a knife. There are two stable isotopes, and four radioisotopes, Tl-204 being the most stable with a half-life of 3.78 years. Thallium sulphate was used as a rodenticide. Thallium sulphine's conductivity changes with exposure to infrared light, this gives it a use in infrared detectors. Discovered by Sir William Crookes via spectroscopy. Its name comes from the Greek word thallos, which means green twig. Thallium and its compounds are toxic and can cause cancer.",
      name_origin: "Greek: thallos (green twig), for a bright green line in its spectrum.",
      sources: "Found in iron pyrites. Also in crookesite, hutchinsonite and lorandite. Most is recovered from the byproducts of lead and zinc refining.",
      uses: "Its compounds are used in rat and ant poisons. Also for detecting infrared radiation.",
      mendeleev_number: "85",
      story: "The discovery of thallium was controversial. William Crookes of the Royal College of Science in London was the first to observe a green line in the spectrum of some impure sulfuric acid, and realised that it meant a new element. He announced his discovery in March 1861 in Chemical News. However, he did very little research into it. Meanwhile, in 1862, Claude-August Lamy of Lille, France, began to research thallium more thoroughly and even cast a small ingot of the metal itself. The French Academy now credited him its discovery. He sent the ingot to the London International Exhibition of 1862, where it was acclaimed as a new metal and he was awarded a medal. Crookes was furious and so the exhibition committee awarded him a medal as well.",
      country: "UK",
      image: "http://res.cloudinary.com/dc2o3efbz/image/upload/v1480905616/elements/thallium-2.jpg",
      formulas: "['TlCl', 'Tl2CO3', 'Tl(NO3)3']",
      formulas_cid: "[24642, 23031, 159690]",
      formula_links: "['/Pcad40eZyg8?si=J22DbQS9gqeFpBzQ', '', '/17IbD0MHXik?si=LToyKQaZly7iUTdl']"
    },
    {
      name: "Lead",
      symbol: "Pb",
      atomic_number: "82",
      atomic_volume: "18.3",
      atomic_weight: "207.2",
      mass_number: "208",
      group: "<Group(symbol=IVA, name=Carbon group)>",
      period: "6",
      series: "Poor metals",
      block: "p",
      electrons: "82",
      protons: "82",
      neutrons: "126",
      cas: "7439-92-1",
      discoverers: "Known to the ancients.",
      discovery_location: "",
      discovery_year: "",
      description: "Heavy dull grey ductile metallic element, belongs to group 14. Used in building construction, lead-place accumulators, bullets and shot, and is part of solder, pewter, bearing metals, type metals and fusible alloys.",
      name_origin: "Anglo-Saxon: lead; symbol from Latin: plumbum.",
      sources: "Found most often in ores called galena or lead sulfide (PbS). Some is found in its native state.",
      uses: "Used in solder, shielding against radiation and in batteries.",
      mendeleev_number: "91",
      story: "Lead has been mined for more than 6,000 years, and the metal and its compounds have been used throughout history. Small lead nuggets have been found in pre-Columbian Peru, Yucatan, and Guatemala. The Greeks mined lead on a large scale from 650 onwards and not only knew how to obtain the metal but how to covert this to white lead. Because of its superb covering power, this was the basis of paints for more than 2000 years, until the middle of the last century. The Romans employed lead on a large scale, mining it mainly in Spain and Britain, and using it also for water pipes, coffins, pewter tableware, and to debase their silver coinage. While its mining declined in the Dark Ages it reappeared in Medieval times and found new uses, such as pottery glazes, bullets, and printing type. In the last century it was a fuel additive.",
      country: "ancient",
      image: "http://res.cloudinary.com/dc2o3efbz/image/upload/v1480905633/elements/lead.jpg",
      formulas: "['PbO', 'PbO2', 'Pb(NO3)2']",
      formulas_cid: "[5794, 14827, 16683880]",
      formula_links: "['/watch?v=KeDV3zmowwM&pp=ygURaG93IHRvIGNyZWF0ZSBQYk8%3D', '/watch?v=n9ADhpa9zSo&pp=ygUSaG93IHRvIGNyZWF0ZSBQYk8y', '/aaVAwwG1778?si=LkVlDsLHBKQT1P_8']"
    },
    {
      name: "Bismuth",
      symbol: "Bi",
      atomic_number: "83",
      atomic_volume: "21.3",
      atomic_weight: "208.9804",
      mass_number: "209",
      group: "<Group(symbol=VA, name=Pnictogens)>",
      period: "6",
      series: "Poor metals",
      block: "p",
      electrons: "83",
      protons: "83",
      neutrons: "126",
      cas: "7440-69-9",
      discoverers: "Known to the ancients.",
      discovery_location: "",
      discovery_year: "",
      description: "White crystalline metal with a pink tinge, belongs to group 15. Most diamagnetic of all metals and has the lowest thermal conductivity of all the elements except mercury. Lead-free bismuth compounds are used in cosmetics and medical procedures. Burns in the air and produces a blue flame. In 1753, C.G. Junine first demonstrated that it was different from lead.",
      name_origin: "German: bisemutum, (white mass), Now spelled wismut.",
      sources: "It can be found free in nature and in minerals like bismuthine (Bi2O3) and in bismuth ochre (Bi2O3)",
      uses: "Main use is in pharmaceuticals and low melting point alloys used as fuses.",
      mendeleev_number: "97",
      story: "Bismuth was discovered by an unknown alchemist around 1400 AD. Later that century it was alloyed with lead to make cast type for printers and decorated caskets were being crafted in the metal. Bismuth was often confused with lead; it was likewise a heavy metal and melted at a relatively low temperature making it easy to work. Georgius Agricola in the early 1500s speculated that it was a distinctly different metal, as did Caspar Neuman in the early 1700s, but proof that it was so finally came in 1753 thanks to the work of Claude-François Geoffre. Bismuth was used as an alloying metal in the bronze of the Incas of South America around 1500 AD. Bismuth was not mined as ore but appears to have occurred as the native metal.",
      country: "ancient",
      image: "http://res.cloudinary.com/dc2o3efbz/image/upload/v1480905670/elements/bismuth.jpg",
      formulas: "['Bi2O12S3', 'Bi2O3', 'BiN3O9']",
      formulas_cid: "[198144, , 107711]",
      formula_links: "['', '/4dY5eZ27fsY?si=gYUcOqsempJ1bR4E', '/shorts/5fTGTQAPtXo?si=miLY0NZYUQbBlTQI']"
    },
    {
      name: "Polonium",
      symbol: "Po",
      atomic_number: "84",
      atomic_volume: "22.7",
      atomic_weight: "209.0",
      mass_number: "186",
      group: "<Group(symbol=VIA, name=Chalcogens)>",
      period: "6",
      series: "Metalloids",
      block: "p",
      electrons: "84",
      protons: "84",
      neutrons: "102",
      cas: "7440-08-6",
      discoverers: "Pierre and Marie Curie",
      discovery_location: "France",
      discovery_year: "1898.0",
      description: "Rare radioactive metallic element, belongs to group 16 of the periodic table. Over 30 known isotopes exist, the most of all elements. Po-209 has a half-life of 103 years. Possible uses in heating spacecraft. Discovered by Marie Curie in 1898 in a sample of pitchblende.",
      name_origin: "Named for Poland, native country of Marie Curie.",
      sources: "Occurs in pitchblende from decay of bismuth.",
      uses: "Used in industrial equipment that eliminates static electricity caused by such processes as rolling paper, wire, and sheet metal.",
      mendeleev_number: "103",
      story: "Uranium ores contain minute traces of polonium at levels of parts per billion. Despite this, in 1898 Marie Curie and husband Pierre Curie extracted some from pitchblende (uranium oxide, U3O8) after months of painstaking work. The existence of this element had been forecast by the Mendeleev who could see from his periodic table that there might well be the element that followed bismuth and he predicted it would have an atomic weight of 212. The Curies had extracted the isotope polonium-209 and which has a half-life of 103 years. Before the advent of nuclear reactors, the only source of polonium was uranium ore but that did not prevent its being separated and used in anti-static devices. These relied on the alpha particles that polonium emits to neutralise electric charge.",
      country: "France",
      image: "http://res.cloudinary.com/dc2o3efbz/image/upload/v1480905692/elements/polonium.jpg",
      formulas: "['Po', 'PoO2', 'PoCl2']",
      formulas_cid: "['6328143', 16745749, 22445]",
      formula_links: "['/bbr5yWwsI1o?si=uJhHcpWHqsIxERGJ', '/watch?v=iiR2IN5_Br4&pp=ygUSaG93IHRvIGNyZWF0ZSBQb08y', '\"\"']"
    },
    {
      name: "Astatine",
      symbol: "At",
      atomic_number: "85",
      atomic_volume: "",
      atomic_weight: "210.0",
      mass_number: "191",
      group: "<Group(symbol=VIIA, name=Halogens)>",
      period: "6",
      series: "Halogens",
      block: "p",
      electrons: "85",
      protons: "85",
      neutrons: "106",
      cas: "7440-68-8",
      discoverers: "D.R.Corson, K.R.MacKenzie, E.Segré",
      discovery_location: "United States",
      discovery_year: "1940.0",
      description: "Radioactive halogen element. Occurs naturally from uranium and thorium decay. At least 20 known isotopes. At-210, the most stable, has a half-life of 8.3 hours. Synthesized by nuclear bombardment in 1940 by D.R. Corson, K.R. MacKenzie and E. Segre at the University of California.",
      name_origin: "Greek: astatos (unstable).",
      sources: "Does not occur in nature. Similar to iodine. Produced by bombarding bismuth with alpha particles.",
      uses: "Since its isotopes have such short half-lives there are no commercially significant compounds of astatine.",
      mendeleev_number: "110",
      story: "In 1939, two groups came near to discovering this element in mineral samples. Horia Hulubei and Yvette Cauchois analysed mineral samples using a high-resolution X-ray apparatus and thought they had detected it. Meanwhile, Walter Minder observed the radioactivity of radium and said it appeared have another element present. He undertook chemical tests which suggested it was like iodine. Element 85 was convincingly produced for the first time at the University of California in 1940 by Dale R. Corson, K.R. Mackenzie, and Emilio Segré. Their astatine was made by bombarding bismuth with alpha particles. Although they reported their discovery, they were unable to carry on with their research due to World War II and the demands of the Manhattan project which diverted all researchers of radioactive materials towards the making of nuclear weapons.",
      country: "USA",
      image: "http://res.cloudinary.com/dc2o3efbz/image/upload/v1480905845/elements/astatine-300x225.jpg",
      formulas: "['At2', 'AtCl', 'AtH']",
      formulas_cid: "[104931, 5459963, '']",
      formula_links: "['/GP8jJgzEmwE?si=THLobHg4Jq-8xeN-', '\"\"', '\"\"']"
    },
    {
      name: "Radon",
      symbol: "Rn",
      atomic_number: "86",
      atomic_volume: "",
      atomic_weight: "222.0",
      mass_number: "193",
      group: "<Group(symbol=VIIIA, name=Noble gases)>",
      period: "6",
      series: "Noble gases",
      block: "p",
      electrons: "86",
      protons: "86",
      neutrons: "107",
      cas: "10043-92-2",
      discoverers: "Fredrich Ernst Dorn",
      discovery_location: "Germany",
      discovery_year: "1898.0",
      description: "Colorless radioactive gaseous element, belongs to the noble gases. Of the twenty known isotopes, the most stable is Rn-222 with a half-life of 3.8 days. Formed by the radioactive decay of Radium-226. Radon itself decays into Polonium. Used in radiotherapy. As a noble gas, it is effectively inert, though radon fluoride has been synthesized. First isolated in 1908 by Ramsey and Gray.",
      name_origin: "Variation of the name of another element, radium.",
      sources: "Formed from the decay of radium in the earths crust.",
      uses: "Used to treat some forms of cancer.",
      mendeleev_number: "117",
      story: "In 1899, Ernest Rutherford and Robert B. Owens detected a radioactive gas being released by thorium. That same year, Pierre and Marie Curie detected a radioactive gas emanating from radium. In1900, Friedrich Ernst Dorn at Halle, Germany, noted that a gas was accumulating inside ampoules of radium. They were observing radon. That from radium was the longer-lived isotope radon-222 which has a half-life 3.8 days, and was the same isotope which the Curies has observed. The radon that Rutherford detected was radon-220 with a half-life of 56 seconds. In 1900, Rutherford devoted himself to investigating the new gas and showed that it was possible to condense it to a liquid. In 1908, William Ramsay and Robert Whytlaw-Gray at University College, London, collected enough radon to determine its properties and reported that it was the heaviest gas known.",
      country: "Germany",
      image: "http://res.cloudinary.com/dc2o3efbz/image/upload/v1480905721/elements/radon.jpg",
      formulas: "['Rn', '', '']",
      formulas_cid: "[24857, ,]",
      formula_links: "['/mTuC_LrEfbU?si=sEJsE8Sicx55YbKR', '', '']"
    },
    {
      name: "Francium",
      symbol: "Fr",
      atomic_number: "87",
      atomic_volume: "",
      atomic_weight: "223.0",
      mass_number: "197",
      group: "<Group(symbol=IA, name=Alkali metals)>",
      period: "7",
      series: "Alkali metals",
      block: "s",
      electrons: "87",
      protons: "87",
      neutrons: "110",
      cas: "7440-73-5",
      discoverers: "Marguerite Derey",
      discovery_location: "France",
      discovery_year: "1939.0",
      description: "Radioactive element, belongs to group 1 of the periodic table. Found in uranium and thorium ores. The 22 known isotopes are all radioactive, with the most stable being Fr-223. Its existence was confirmed in 1939 by Marguerite Perey.",
      name_origin: "Named for France, the nation of its discovery.",
      sources: "Formed by decay of actinium. Chemical properties similar to cesium. Decays to radium or astatine.",
      uses: "Since its isotopes have such short half-lives there are no commercially significant compounds of francium.",
      mendeleev_number: "6",
      story: "Mendeleev said there should be an element like caesium waiting to be discovered. Consequently, there were claims, denials, and counterclaims by scientists who said they had found it. During the 1920s and 30s, these claims were made on the basis of unexplained radioactivity in minerals, or new lines in their X-ray spectra, but all eventually turned out not to be evidence of element 87. Francium was finally discovered in 1939 by Marguerite Perey at the Curie Institute in Paris. She had purified a sample of actinium free of all its known radioactive impurities and yet its radioactivity still indicated another element was present, and which she rightly deduced was the missing element 87. Others challenged her results too, and it was not until after World War II that she was accepted as the rightful discoverer in 1946.",
      country: "France",
      image: "http://res.cloudinary.com/dc2o3efbz/image/upload/v1480905808/elements/francium.jpg",
      formulas: "['Fr', '', '']",
      formulas_cid: "[6328145, ,]",
      formula_links: "['/hpYxllgfMSg?si=a2yPcuEIhiiuCEzO', '', '']"
    },
    {
      name: "Radium",
      symbol: "Ra",
      atomic_number: "88",
      atomic_volume: "45.0",
      atomic_weight: "226.0",
      mass_number: "201",
      group: "<Group(symbol=IIA, name=Alkaline earths)>",
      period: "7",
      series: "Alkaline earth metals",
      block: "s",
      electrons: "88",
      protons: "88",
      neutrons: "113",
      cas: "7440-14-4",
      discoverers: "Pierre and Marie Curie",
      discovery_location: "France",
      discovery_year: "1898.0",
      description: "Radioactive metallic transuranic element, belongs to group 2 of the periodic table. Most stable isotope, Ra-226 has a half-life of 1602 years, which decays into radon. Isolated from pitchblende in 1898 Marie and Pierre Curie.",
      name_origin: "Latin: radius (ray).",
      sources: "Found in uranium ores at 1 part per 3 million parts uranium.",
      uses: "Used in treating cancer because of the gamma rays it gives off.",
      mendeleev_number: "10",
      story: "Radium was discovered in 1898 by Marie Curie and Pierre Curie. They managed to extract 1 mg of radium from ten tonnes of the uranium ore pitchblende (uranium oxide, U3O8), a considerable feat, given the chemically methods of separation available to them. They identified that it was a new element because its atomic spectrum revealed new lines. Their samples glowed with a faint blue light in the dark, caused by the intense radioactivity exciting the surrounding air. The metal itself was isolated by Marie Curie and André Debierne in 1911, by means of the electrolysis of radium chloride. At Debierne’s suggestion, they used a mercury cathode in which the liberated radium dissolved. This was then heated to distil off the mercury leaving the radium behind.",
      country: "France",
      image: "http://res.cloudinary.com/dc2o3efbz/image/upload/v1480905917/elements/radium-glow.jpg",
      formulas: "['Ra', '', '']",
      formulas_cid: "[6328144, ,]",
      formula_links: "['/I_1XelLa1eo?si=DwwIz4WVPex7Ew5Q', '', '']"
    },
    {
      name: "Actinium",
      symbol: "Ac",
      atomic_number: "89",
      atomic_volume: "22.54",
      atomic_weight: "227.0",
      mass_number: "205",
      group: "<Group(symbol=IIIB, name=)>",
      period: "7",
      series: "Actinides",
      block: "d",
      electrons: "89",
      protons: "89",
      neutrons: "116",
      cas: "7440-34-8",
      discoverers: "André Debierne",
      discovery_location: "France",
      discovery_year: "1899.0",
      description: "Silvery radioactive metallic element, belongs to group 3 of the periodic table. The most stable isotope, Ac-227, has a half-life of 217 years. Ac-228 (half-life of 6.13 hours) also occurs in nature. There are 22 other artificial isotopes, all radioactive and having very short half-lives. Chemistry similar to lanthanumpy. Used as a source of alpha particles. Discovered by A. Debierne in 1899.",
      name_origin: "Greek: akis, aktinos (ray).",
      sources: "Extremely rare, found in all uranium ores. Usually obtained by treating radium with neutrons in a reactor.",
      uses: "It has no significant commercial applications.",
      mendeleev_number: "14",
      story: "This element was discovered in 1899 by André Debierne at Paris. He extracted it from the uranium ore pitchblende (uranium oxide, U3O8) in which it occurs in trace amounts. In 1902, Friedrich Otto Giesel independently extracted it from the same mineral and, unaware it was already known, gave it the named emanium. Actinium extracted from uranium ores is the isotope actinium-227 which has half-life of 21.7 years. It occurs naturally as one of the sequence of isotopes that originate with the radioactive decay of uranium-235. A tonne of pitchblende contains around 150 mg of actinium.",
      country: "France",
      image: "http://res.cloudinary.com/dc2o3efbz/image/upload/v1480906342/elements/actinium.jpg",
      formulas: "['Ac', 'AcN3O9', '']",
      formulas_cid: "[23965, 162623744, ]",
      formula_links: "['/rKm0ShaJNFM?si=gIkSznzt9NreDbwv', '', '']"
    },
    {
      name: "Thorium",
      symbol: "Th",
      atomic_number: "90",
      atomic_volume: "19.8",
      atomic_weight: "232.0377",
      mass_number: "232",
      group: "",
      period: "7",
      series: "Actinides",
      block: "f",
      electrons: "90",
      protons: "90",
      neutrons: "142",
      cas: "7440-29-1",
      discoverers: "Jöns Berzelius",
      discovery_location: "Sweden",
      discovery_year: "1828.0",
      description: "Grey radioactive metallic element. Belongs to actinoids. Found in monazite sand in Brazil, India and the US. Thorium-232 has a half-life of 1.39x10^10 years. Can be used as a nuclear fuel for breeder reactors. Thorium-232 captures slow Neutrons and breeds uranium-233. Discovered by Jons J. Berzelius in 1829.",
      name_origin: "Named for Thor, Norse god of thunder.",
      sources: "Found in various minerals like monazite and thorite.",
      uses: "Used in making strong alloys. Also in ultraviolet photoelectric cells. It is a common ingredient in high-quality lenses. Bombarded with neutrons make uranium-233, a nuclear fuel.",
      mendeleev_number: "16",
      story: "In 1829, Jöns Jakob Berzelius of the Royal Karolinska Institute, Stockholm extracted thorium from a rock specimen sent to him by an amateur mineralogist who had discovered it near Brevig and realised that it had not previously been reported. The mineral turned out to be thorium silicate, and it is now known as thorite. Berzelius even produced a sample of metallic thorium by heating thorium fluoride with potassium, and confirmed it as a new metal. The radioactivity of thorium was first demonstrated in 1898 by Gerhard Schmidt and confirmed by Marie Curie. Thorium, like uranium, survives on Earth because it has isotopes with long half-lives, such as the predominant one, thorium-232, whose half life is 14 billion years.",
      country: "Sweden",
      image: "http://res.cloudinary.com/dc2o3efbz/image/upload/v1480906354/elements/thorium.jpg",
      formulas: "['ThO2', 'ThF4', 'ThCl4']",
      formulas_cid: "[14808, 5460747, 66209]",
      formula_links: "['/watch?v=QjTyDpPkD3A&pp=ygUSaG93IHRvIGNyZWF0ZSBUaE8y', '\"\"', '\"\"']"
    }
  ]